create table "CUSTOMERS" (
	"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	"NAME" VARCHAR(250),
	"EMAIL" VARCHAR(250),
	"PASSWORD" VARCHAR(250)
);

ALTER TABLE "CUSTOMERS" ADD CONSTRAINT "SQL120325130144011" PRIMARY KEY ("ID");